[versions]
agp = "8.13.1"
coilCompose = "2.7.0"
hiltAndroidTesting = "2.50"
kotlin = "2.0.0"
coreKtx = "1.15.0"
coreSplashscreen = "1.0.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.0"
composeBom = "2025.02.00"
room = "2.6.1"
ksp = "2.0.0-1.0.21"
hilt = "2.50"
hiltCommon = "1.2.0"
hiltNavigation = "1.2.0"
composeNavigation = "2.8.7"
serialization = "1.6.3"
workRuntimeKtx = "2.10.0"
androidx_datastore = "1.1.7"
fragment-ktx = "1.8.6"
retrofit = "2.9.0"
okhttp = "4.9.1"
moshi = "1.14.0"
lifecycleCommonJava8 = "2.8.7"
material = "1.12.0"
camera = "1.5.0-alpha05"
accompanist = "0.30.1"
material2 = "1.7.9"
rules = "1.6.1"
sdkVersion = "1.19.3"
uiTextGoogleFonts = "1.8.3"
mlkitBarcode = "17.3.0"
zxing = "3.5.3"
playCodeScanner = "16.1.0"
cameraCore = "1.5.2"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidTesting" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }

room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigation" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltCommon" }

navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx_datastore" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx_datastore" }

retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit2-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }

androidx-lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycleCommonJava8" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camera" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }
camera-video = { group = "androidx.camera", name = "camera-video", version.ref = "camera" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }

accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }

androidx-material = { group = "androidx.compose.material", name = "material" }
androidx-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

lunaid-core = { group = "ai.visionlabs.lunaid", name = "core", version.ref = "sdkVersion" }
lunaid-common-arm = { group = "ai.visionlabs.lunaid", name = "common-arm", version.ref = "sdkVersion" }
lunaid-cnn60-arm = { group = "ai.visionlabs.lunaid", name = "cnn60-arm", version.ref = "sdkVersion" }
lunaid-mask-arm = { group = "ai.visionlabs.lunaid", name = "mask-arm", version.ref = "sdkVersion" }
lunaid-glasses-arm = { group = "ai.visionlabs.lunaid", name = "glasses-arm", version.ref = "sdkVersion" }
lunaid-mouthestimator-arm = { group = "ai.visionlabs.lunaid", name = "mouthestimator-arm", version.ref = "sdkVersion" }
lunaid-oslm-arm = { group = "ai.visionlabs.lunaid", name = "oslm-arm", version.ref = "sdkVersion" }
lunaid-security = { group = "ai.visionlabs.lunaid", name = "security", version.ref = "sdkVersion" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
mlkit-barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "mlkitBarcode" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
play-services-code-scanner = { group = "com.google.android.gms", name = "play-services-code-scanner", version.ref = "playCodeScanner" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }


